#!/bin/bash
# Generate Supabase config from environment variables
# This runs during Netlify build

CONFIG_FILE="assets/js/supabase-config.js"

echo "// Auto-generated by generate-config.sh during build" > $CONFIG_FILE
echo "// DO NOT EDIT MANUALLY - This file is generated from environment variables" >> $CONFIG_FILE
echo "" >> $CONFIG_FILE
echo "window.SUPABASE_URL = '${SUPABASE_URL:-}';" >> $CONFIG_FILE
echo "window.SUPABASE_ANON_KEY = '${SUPABASE_ANON_KEY:-}';" >> $CONFIG_FILE

echo "✅ Generated $CONFIG_FILE with Supabase configuration"
